# Runtimes used by the stack.
[tools]
gleam = "1.3.2"
erlang = "27"
node = "22"
deno = "latest"

# Environment variables shared by all applications.
[env]
NODE_ENV = "development"
GLEAM_ENV = "development"
