# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

name = "frontend"
target = "javascript"
version = "1.0.0"

[javascript]
typescript_declarations = true

[dependencies]
birl = ">= 1.7.1 and < 2.0.0"
bright = {path = "../../packages/bright"}
gleam_fetch = ">= 0.4.0 and < 1.0.0"
gleam_http = ">= 3.7.1 and < 4.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"
gleam_json = ">= 2.1.0 and < 3.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = "~> 0.34 or ~> 1.0"
grille_pain = ">= 1.1.0 and < 2.0.0"
interfaces = {path = "../../packages/interfaces"}
lustre = ">= 4.6.1 and < 5.0.0"
modem = ">= 2.0.0 and < 3.0.0"
sketch = ">= 3.0.0 and < 4.0.0"
sketch_magic = {path = "../../packages/sketch_magic"}
vitools = {path = "../../packages/vitools"}

[dev-dependencies]
gleeunit = "~> 1.0"
