name = "backend"
version = "1.0.0"

[dependencies]
gleam_erlang = "~> 0.25"
gleam_http = "~> 3.6"
gleam_json = "~> 1.0"
gleam_stdlib = "~> 0.34 or ~> 1.0"
mist = "1.0.0-rc2"
radiate = {path = "../../packages/gleam-radiate"}
wisp = "~> 0.14"

[dev-dependencies]
gleeunit = "~> 1.0"
