name = "backend"
version = "1.0.0"

[dependencies]
birl = "~> 1.6"
dot_env = "~> 0.5"
gleam_erlang = "~> 0.25"
gleam_http = "~> 3.6"
gleam_json = "~> 1.0"
gleam_otp = "~> 0.10"
gleam_package_interface = ">= 1.0.0 and < 2.0.0"
gleam_pgo = "~> 0.7"
gleam_stdlib = "~> 0.34 or ~> 1.0"
mist = "1.0.0-rc2"
pgo = "~> 0.14"
radiate = {path = "../../packages/gleam-radiate"}
simplifile = ">= 1.7.0 and < 2.0.0"
wisp = "~> 0.14"
gleam_hexpm = "~> 1.0"
gleam_httpc = ">= 2.2.0 and < 3.0.0"
tom = ">= 0.3.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
pprint = ">= 1.0.3 and < 2.0.0"
