name = "plasma"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
verl = ">= 1.1.0 and < 2.0.0"
youid = ">= 1.5.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
