name = "jupiter"
version = "1.0.0"

[dependencies]
aws4_request = ">= 1.2.0 and < 2.0.0"
cell = ">= 1.0.0 and < 2.0.0"
chomp = {path = "../../packages/chomp"}
cors_builder = ">= 2.0.0 and < 3.0.0"
envoy = ">= 1.0.0 and < 2.0.0"
exception = ">= 2.1.0 and < 3.0.0"
galaxy = {path = "../../packages/galaxy"}
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_hexpm = ">= 3.0.0 and < 4.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_package_interface = ">= 3.0.0 and < 4.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
glexer = ">= 2.0.0 and < 3.0.0"
mist = ">= 5.0.0 and < 6.0.0"
palabres = ">= 1.0.0 and < 2.0.0"
plasma = {path = "../../packages/plasma"}
pog = ">= 4.0.0 and < 5.0.0"
prng = ">= 5.0.0 and < 6.0.0"
ranger = ">= 1.4.0 and < 2.0.0"
simplifile = ">= 2.1.0 and < 3.0.0"
tom = ">= 2.0.0 and < 3.0.0"
wisp = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
