name: Deploy demo

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0.0"
          gleam-version: "1.6.1"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Downloading dependencies
        run: gleam deps download
        working-directory: e2e/sample
      - name: Build demo
        run: gleam run -m lustre/dev build
        working-directory: e2e/sample
      - name: Copy files
        run: |
          mkdir _site
          cp -r e2e/sample/priv _site
          cp e2e/sample/index.html _site
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
