name = "app"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.36"
lustre = { path = "../../" }
lustre_ui = "~> 0.4"

[dev-dependencies]
gleeunit = "~> 1.0"
lustre_dev_tools = "~> 1.0"
